site_name: Blueberry Docs
repo_url: https://github.com/BlueberryMC/Blueberry
repo_name: BlueberryMC/Blueberry
theme:
  name: material
  logo: assets/blueberry.png
  favicon: assets/blueberry.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: light blue
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: light blue
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.sections
nav:
  - BlueberryMC:
    - index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/built-in-commands.md
    - Creating a mod:
      - getting-started/creating-a-mod/index.md
      - getting-started/creating-a-mod/event-api.md
      - getting-started/creating-a-mod/client-commands.md
      - getting-started/creating-a-mod/registering-an-item.md
      - getting-started/creating-a-mod/event-api-legacy.md
  - Reference:
    - reference/mod-yml-format.md
    - reference/mixin.md
    - reference/source-mod.md
  - Changelogs:
    - changelogs/1.18.2-1.4.1.md
    - changelogs/1.18.2-1.4.0.md
    - changelogs/1.18.2-1.3.1.md
    - changelogs/1.18.2-1.3.0.md
    - changelogs/1.18.2-1.2.0.md
    - changelogs/1.18.2-1.1.0.md
    - changelogs/1.18.2-1.0.0.md
    - changelogs/1.18.1-0.2.2.md
    - changelogs/1.18.1-0.2.1.md
    - changelogs/1.18.1-0.2.0.md
    - changelogs/1.18-0.1.0.md
    - changelogs/1.18-0.0.19.md
    - changelogs/1.18-0.0.18.md
    - changelogs/1.18-0.0.17.md
markdown_extensions:
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - md_in_html
  - tables
  - meta
  - footnotes # https://squidfunk.github.io/mkdocs-material/reference/footnotes/#adding-footnote-references
  - abbr # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#adding-abbreviations
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 
# extra:
#   version:
#     provider: mike
